### ISSUE TITLE
Nav menu covers hero area when wrapping on tablet

### ISSUE THREAD

**Issue by frankiejarrett** [godaddy/wp-mins-theme#16]
Similar issue to https://github.com/godaddy/wp-lyrical-theme/issues/19.

What do you think @chriswallace? Should we just use the mobile nav on tablet too on all the themes? I think it would prevent this from ever happening in the majority of cases.

<img width="731" alt="screen shot 2016-08-26 at 2 35 42 pm" src="https://cloud.githubusercontent.com/assets/522158/18018061/6ac0acda-6b9a-11e6-820c-479813ef6656.png">

**Comment by chriswallace** [comment]
The trouble is we never know exactly how many menu items might exist in the user's nav menu. Better solution is to let the header area extend down and push the hero down below as needed. Or write a complicated set of javascript that hides menu items behind an ellipses until you get to your small breakpoint. But that would be complicated and I think it's unnecessary for most sites.
