### ISSUE TITLE
Need function to remove title from hero 

### ISSUE THREAD

**Issue by samonja** [godaddy/wp-mins-theme#29]
i like the theme but I dont like that page title is in the hero on the top. Is there a function to remove the title from the hero banner. Thanks

**Comment by jonathanbardo** [comment]
@samonja You will need to create a custom plugin and add the following snippet:
```php
add_action( 'template_redirect', function() {

  remove_action( 'primer_hero', 'primer_add_page_title' );

}, 11 );
```

**Comment by samonja** [comment]
Thanks

**Comment by samonja** [comment]
How do I make the hero stay the same size
