### ISSUE TITLE
missing search box on header

### ISSUE THREAD

**Issue by richardhdc** [godaddy/wp-mins-theme#39]
How to add search box on the header?

**Comment by EvanHerman** [comment]
Hi @richardhdc,

No search bar comes in the header of the mins theme. This is not the default functionality. You can see a demo of the theme here: https://wpnux.godaddy.com/?theme=mins

If you'd like to add a Search form to the header you're best bet is to create an MU plugin and make a few alterations. We have documentation setup outlining how you can create an MU plugin here: https://godaddy.github.io/wp-primer-theme/tutorials-and-examples/tutorials/mu-plugin.html.

Once you have an MU plugin setup, you can add the following code to your plugin to get you headed in the right direction:

```php
/**
 * Display a search form in the Mins site header.
 *
 * @return mixed Markup for the search form.
 */
function header_search_form() {

	get_search_form();

}
add_action( 'primer_after_site_header_wrapper', 'header_search_form' );

```

That should help get you started, you may need to do some tweaking of the CSS to get things looking right.

Evan
