### ISSUE TITLE
Mobile nav issue on iPhone (requires double tap to expand sub menu)

### ISSUE THREAD

**Issue by timborkowski** [godaddy/wp-mins-theme#40]
I've been building a site for a client with the Mins child theme at:

http://nps.kickingdesigns.com

When viewing the main navigation on Safari on an iPhone it take two taps to view the sub menus when it should be just one tap:

![capture](https://user-images.githubusercontent.com/32946343/31801748-37eedaca-b518-11e7-98b1-b81594ff1651.jpg)

In all other browsers, mobile or not it requires only one tap as expected. Would anyone be able to shed light as to why this might be happening and if it can be fixed so it only requires one tap?

Thanks in advance!

Tim

**Comment by EvanHerman** [comment]
Hi @timborkowski 

Sorry for the delay in responding here. This was actually an issue with the child theme, Primer. We've since pushed out an update that should have resolved this issue. If not please let us know and we can re-investigate.

Evan
