### ISSUE TITLE
Adding image slider to hero header

### ISSUE THREAD

**Issue by markvidler84** [godaddy/wp-mins-theme#43]
Hi, is this possible? Or is it best to remove the hero header and create a full width slide show using the page editor?

Thanks in advance

**Comment by EvanHerman** [comment]
Hi @markvidler84 

No, it's not possible using the page builder. You would have to customize some templates or use the available hooks and filters bundled in the theme.

Feel free to take a look at the following WordPress.org thread with a similar question:
https://wordpress.org/support/topic/replacing-hero-image-with-slider/

**Comment by markvidler84** [comment]
Thanks Evan, I'll take a look
