### ISSUE TITLE
Remove Godaddy footer credit

### ISSUE THREAD

**Issue by YanivAro** [godaddy/wp-mins-theme#46]
hi
I'm trying to remove/change godaddy footer credit:

Copyright © 2018 xxxxxxxxxx — Mins theme by GoDaddy

I tried to look for footer.php on mins theme - no luck
i used few plugins to "remove footer credit" - no luck
i search mysql db for this text - no luck 

maybe someone know what should i do to fix this? 

thanks,

yaniv

**Comment by EvanHerman** [comment]
Hi Yaniv

Inside of the customizer our should be able to check/uncheck the option for displaying author credit. You can get the customizer from the dashboard by going to “Appearance > Customize”.

Let us know if you are still unable to remove it. 

Evan
