### ISSUE TITLE
Trouble adding a sidebar to the blog page in Mins

### ISSUE THREAD

**Issue by portugueseninja** [godaddy/wp-mins-theme#57]
Is there something in the Mins theme that doesn't allow an additional sidebar for widgets on a posts page? My client wants a Twitter widget on the blog but whatever I do I can't get one to appear. Tried multiple widgets and plug-ins, and they work fine on static pages but not on the actual blog page.

Also tried following the instructions here:
https://www.tastyplacement.com/add-sidebar-wordpress to register a new sidebar, and couldn't get that to work either.

Any ideas? I'm really stuck!

**Comment by EvanHerman** [comment]
Hi @portugueseninja 

There is nothing built into the theme to prevent you from registering additional sidebars. Are you still looking to achieve this? If so I would be happy to help out.
