### ISSUE TITLE
Documentation?

### ISSUE THREAD

**Issue by lbramirez** [godaddy/wp-mins-theme#58]
Hi - There does not seem to be any documentation, can someone point me in the right direction?  Usually there would be an outline of how to create the look of the Demo's home page. Thx, Laura

**Comment by EvanHerman** [comment]
Hi Laura,

There is nothing built out in that great of detail explaining step by step how to recreate the demo site. We have documentation that can be found at https://godaddy.github.io/wp-primer-theme/index.html. It's a lot of developer documentation with some small tutorials. It looks like that documentation also needs to be updated for the most recent release.
