### ISSUE TITLE
Where is the demo data of this theme ? 

### ISSUE THREAD

**Issue by Forekan3** [godaddy/wp-mins-theme#61]
Hello ,
I have already installed Mins child theme along with Primer Parent theme . But there is no file for importing demo data to make it as same the Mins child theme demo or there is no option in customization or theme option to make it manually as same as demo . Can you anyone please help what is the case? 
Thanks

**Comment by EvanHerman** [comment]
Hi @Forekan3 

There is no demo data bundled with the theme. GoDaddy customers can setup a new site on the Managed WordPress platform with one of these themes, and during that process the demo data is downloaded from our remote server and installed as a starting point for the customer. Outside of our hosting platform, the demo data is not accessible.

Evan
