### ISSUE TITLE
Missing 3 Column Widgets & Setup

### ISSUE THREAD

**Issue by mark2090** [godaddy/wp-mins-theme#75]
This Mins theme is suppose to support 3 columns and suppose to be a child of the Primer theme. 

When I installed it, the page editor does show the settings for various column layouts as it does for Primer, -- but it does not provide the needed widget modules to insert a widget for the left or right side column. 

The "Sidebar" and "Secondary Sidebar" modules are missing from the Mins child theme.

Is this on purpose?

**Comment by aledesma-godaddy** [comment]
Closing issues and PRs in preparation for repository archival
