### ISSUE TITLE
Embedded YouTube video header broken appearance.

### ISSUE THREAD

**Issue by gdandrija** [godaddy/wp-mins-theme#77]
Summary of the issue:
If the website using our Mins child theme loads a video from YouTube in Header media, the appearance is broken due to the fact theme uses an outdated version of jQuery. This happens with the latest WordPress version 5.6

Replication steps:
1) Activate Mins Child theme
2) Go to Customizer > Header Media and set YouTube video to load as a header background.
3) Click Publish and the frontpage will resolve with embedded YT video instead of a background video.

Replicated issue with Primer theme and WP up to date, with all plugins turned off ->https://i.imgur.com/RB2SG4O.jpg

Issue replicated on a test website as well.

Temporary fix - using a plugin like jQuery manager to re-add support for old versions of jQuery migrate.

The issue initially submitted on WordPress.org: https://wordpress.org/support/topic/problem-with-header-media-background-video-since-update/

**Comment by gdandrija** [comment]
More people reporting this issue on WordPress.org, any updates?

**Comment by steeeeev0** [comment]
Having the same issue, hoping for a fix soon!

**Comment by PageTown** [comment]
New version of WordPress dropped yesterday. This problem has not been corrected.

**Comment by aledesma-godaddy** [comment]
Closing issues and PRs in preparation for repository archival
